name: remote ssh command
on: [push]
jobs:
  transfer-new-files:
    name: Transfer Files & Run Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "*"
        target: "/home/ubuntu/Discord_Bot/rules_branch"
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        
        script: |
          touch ~/rules_command_step1.txt
          export COSCYBOT=${{ secrets.RULESBRANCH }}
          export PGPASSWORD=${{ secrets.DBPSWD }}
          export PGUSER=${{ secrets.DBUSER }}
          export PGPORT=${{ secrets.DBPORT }}
          export PGHOST=${{ secrets.DBHOST }}
          export PGDATABASE=${{ secrets.DBNAME }}
          touch ~/rules_command_step2.txt
          sh Discord_Bot/rules_branch/startup.sh
          touch ~/rule_command_steps_completed.txt
