name: remote ssh command
on: [push]
jobs:
  transfer-new-files:
    name: Transfer Files & Run Application
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "*"
        target: "/home/ubuntu/Discord_Bot"
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        
        script: |
          touch ~/FirstStep.txt
          touch /home/ubuntu/FirstStep2.txt
          if pgrep -f Discord_Bot; then kill $(pgrep -f Discord_Bot); fi
          export NARVIS=${{ secrets.NARVIS }}
          node ~/Discord_Bot/main.js &
          touch ~/SecondStep.txt
          touch /home/ubuntu/SecondStep2.txt
